services:
    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel_docker_image
        container_name: laravel_docker_container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel_docker_network
    mysql:
        image: mysql:8.0
        container_name: laravel_docker_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql_data:/var/lib/mysql
        networks:
            - laravel_docker_network
    nginx:
        image: nginx:alpine
        container_name: laravel_docker_nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel_docker_network
    redis:
        image: redis:alpine
        container_name: laravel_docker_redis
        restart: unless-stopped
        networks:
            - laravel_docker_network
networks:
    laravel_docker_network:
        driver: bridge
volumes:
    mysql_data:
